<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <CreateCipx>true</CreateCipx>
    <RootNamespace>ClassIsland.Control.Plugin</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ClassIsland.PluginSdk" Version="2.1.0.1">
      <ExcludeAssets>runtime; native</ExcludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <None Update="manifest.yml" CopyToOutputDirectory="PreserveNewest" />
    <None Update="README.md" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
